import {
  Brain,
  Compass,
  Lightbulb,
  Target,
  Users,
  User as UserIcon,
  Sparkles,
  Layers,
  ListChecks,
  CheckSquare,
  Flag,
  GitBranch,
  AlertTriangle,
  HelpCircle,
  FlaskConical,
  BookOpen,
  MessagesSquare,
  Boxes,
  Phone,
  Cpu,
  Server,
  DollarSign,
  Package as PackageIcon,
  Calculator,
  Gauge,
  Briefcase,
  Megaphone,
  Building,
  Rocket,
  LucideIcon,
} from "lucide-react";
import type { RecordType, Module } from "@prisma/client";

export type ModuleKey = Module;

export interface EntityMeta {
  type: RecordType;
  label: string;
  labelPlural: string;
  slug: string;
  module: ModuleKey;
  icon: LucideIcon;
  description: string;
  mvp: boolean;
  defaultStatus: string;
  statuses: string[];
  /** Extra type-specific fields stored under Record.data (JSON). */
  dataFields?: Array<{
    key: string;
    label: string;
    kind: "text" | "textarea" | "number" | "enum" | "list";
    options?: string[];
  }>;
}

export const ENTITIES: Record<RecordType, EntityMeta> = {
  idea: {
    type: "idea",
    label: "Idea",
    labelPlural: "Ideas",
    slug: "ideas",
    module: "strategy",
    icon: Lightbulb,
    description: "Quick-capture raw thought, later promoted.",
    mvp: true,
    defaultStatus: "new",
    statuses: ["new", "triaged", "promoted", "dropped"],
    dataFields: [
      { key: "source", label: "Source", kind: "text" },
      {
        key: "intendedDestination",
        label: "Intended destination",
        kind: "enum",
        options: ["problem", "feature", "decision", "experiment", "task", "none"],
      },
    ],
  },
  vision: {
    type: "vision",
    label: "Vision",
    labelPlural: "Vision statements",
    slug: "visions",
    module: "strategy",
    icon: Compass,
    description: "Strategic vision statements.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
    dataFields: [
      { key: "targetOutcome", label: "Target outcome", kind: "textarea" },
      { key: "horizon", label: "Horizon", kind: "text" },
    ],
  },
  thesis: {
    type: "thesis",
    label: "Thesis",
    labelPlural: "Theses",
    slug: "theses",
    module: "strategy",
    icon: Brain,
    description: "Product / market theses.",
    mvp: false,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
    dataFields: [
      { key: "thesisStatement", label: "Thesis statement", kind: "textarea" },
      { key: "supportingTrends", label: "Supporting trends", kind: "list" },
    ],
  },
  problem: {
    type: "problem",
    label: "Problem",
    labelPlural: "Problems",
    slug: "problems",
    module: "strategy",
    icon: Target,
    description: "Customer problem statements.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
    dataFields: [
      { key: "affectedPersona", label: "Affected persona", kind: "text" },
      {
        key: "evidenceStrength",
        label: "Evidence strength",
        kind: "enum",
        options: ["low", "medium", "high"],
      },
      {
        key: "urgency",
        label: "Urgency",
        kind: "enum",
        options: ["low", "medium", "high"],
      },
      {
        key: "frequency",
        label: "Frequency",
        kind: "enum",
        options: ["rare", "occasional", "frequent", "constant"],
      },
    ],
  },
  icp: {
    type: "icp",
    label: "ICP",
    labelPlural: "ICPs",
    slug: "icps",
    module: "strategy",
    icon: Users,
    description: "Ideal customer profiles.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
    dataFields: [
      { key: "segment", label: "Segment", kind: "text" },
      { key: "industry", label: "Industry", kind: "text" },
      { key: "companySize", label: "Company size", kind: "text" },
      { key: "geography", label: "Geography", kind: "text" },
      { key: "buyerType", label: "Buyer type", kind: "text" },
      { key: "userType", label: "User type", kind: "text" },
      { key: "currentPain", label: "Current pain", kind: "textarea" },
      { key: "triggerEvents", label: "Trigger events", kind: "list" },
      { key: "budgetFit", label: "Budget fit", kind: "text" },
      { key: "salesComplexity", label: "Sales complexity", kind: "text" },
    ],
  },
  persona: {
    type: "persona",
    label: "Persona",
    labelPlural: "Personas",
    slug: "personas",
    module: "gtm",
    icon: UserIcon,
    description: "Buyer / user personas.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
    dataFields: [
      { key: "role", label: "Role", kind: "text" },
      { key: "pains", label: "Pains", kind: "list" },
      { key: "buyingTriggers", label: "Buying triggers", kind: "list" },
      { key: "objections", label: "Objections", kind: "list" },
      { key: "successMetrics", label: "Success metrics", kind: "list" },
      { key: "preferredLanguage", label: "Preferred language", kind: "text" },
      { key: "salesCycleNotes", label: "Sales cycle notes", kind: "textarea" },
    ],
  },
  differentiator: {
    type: "differentiator",
    label: "Differentiator",
    labelPlural: "Differentiators",
    slug: "differentiators",
    module: "strategy",
    icon: Sparkles,
    description: "Positioning differentiators.",
    mvp: false,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "validated", "archived"],
  },
  epic: {
    type: "epic",
    label: "Epic",
    labelPlural: "Epics",
    slug: "epics",
    module: "roadmap",
    icon: Layers,
    description: "Large roadmap chunks.",
    mvp: true,
    defaultStatus: "backlog",
    statuses: [
      "backlog",
      "scoping",
      "ready",
      "in_progress",
      "blocked",
      "in_review",
      "done",
      "dropped",
    ],
  },
  feature: {
    type: "feature",
    label: "Feature",
    labelPlural: "Features",
    slug: "features",
    module: "roadmap",
    icon: ListChecks,
    description: "Roadmap features.",
    mvp: true,
    defaultStatus: "backlog",
    statuses: [
      "backlog",
      "scoping",
      "ready",
      "in_progress",
      "blocked",
      "in_review",
      "done",
      "dropped",
    ],
    dataFields: [
      { key: "whyItMatters", label: "Why it matters", kind: "textarea" },
      { key: "userOutcome", label: "User outcome", kind: "textarea" },
      { key: "adminOutcome", label: "Admin outcome", kind: "textarea" },
      { key: "technicalNotes", label: "Technical notes", kind: "textarea" },
      { key: "effortEstimate", label: "Effort estimate", kind: "text" },
      { key: "businessValue", label: "Business value", kind: "text" },
      { key: "acceptanceCriteria", label: "Acceptance criteria", kind: "list" },
      { key: "nfrImplications", label: "NFR implications", kind: "list" },
    ],
  },
  story: {
    type: "story",
    label: "Story",
    labelPlural: "Stories",
    slug: "stories",
    module: "roadmap",
    icon: BookOpen,
    description: "User stories.",
    mvp: false,
    defaultStatus: "backlog",
    statuses: [
      "backlog",
      "scoping",
      "ready",
      "in_progress",
      "blocked",
      "in_review",
      "done",
      "dropped",
    ],
  },
  task: {
    type: "task",
    label: "Task",
    labelPlural: "Tasks",
    slug: "tasks",
    module: "delivery",
    icon: CheckSquare,
    description: "Delivery / execution tasks.",
    mvp: true,
    defaultStatus: "backlog",
    statuses: [
      "backlog",
      "scoping",
      "ready",
      "in_progress",
      "blocked",
      "in_review",
      "done",
      "dropped",
    ],
    dataFields: [
      { key: "dueDate", label: "Due date", kind: "text" },
      { key: "workstream", label: "Workstream", kind: "text" },
      { key: "completionNotes", label: "Completion notes", kind: "textarea" },
    ],
  },
  milestone: {
    type: "milestone",
    label: "Milestone",
    labelPlural: "Milestones",
    slug: "milestones",
    module: "delivery",
    icon: Flag,
    description: "Named milestones.",
    mvp: true,
    defaultStatus: "not_started",
    statuses: ["not_started", "in_progress", "ready", "blocked"],
    dataFields: [
      { key: "targetDate", label: "Target date", kind: "text" },
      { key: "workstream", label: "Workstream", kind: "text" },
      { key: "criteria", label: "Criteria", kind: "list" },
    ],
  },
  decision: {
    type: "decision",
    label: "Decision",
    labelPlural: "Decisions",
    slug: "decisions",
    module: "decisions",
    icon: GitBranch,
    description: "Decision records (including ADRs).",
    mvp: true,
    defaultStatus: "proposed",
    statuses: ["proposed", "under_review", "approved", "rejected", "superseded"],
    dataFields: [
      {
        key: "domain",
        label: "Domain",
        kind: "enum",
        options: ["strategy", "architecture", "pricing", "gtm", "ops"],
      },
      { key: "context", label: "Context", kind: "textarea" },
      { key: "options", label: "Options considered", kind: "list" },
      { key: "chosenOption", label: "Chosen option", kind: "textarea" },
      { key: "whyChosen", label: "Why chosen", kind: "textarea" },
      { key: "tradeOffs", label: "Trade-offs", kind: "textarea" },
      { key: "consequences", label: "Consequences", kind: "textarea" },
      { key: "reviewDate", label: "Review date", kind: "text" },
    ],
  },
  assumption: {
    type: "assumption",
    label: "Assumption",
    labelPlural: "Assumptions",
    slug: "assumptions",
    module: "risks",
    icon: HelpCircle,
    description: "Assumption log.",
    mvp: true,
    defaultStatus: "unvalidated",
    statuses: ["unvalidated", "validating", "validated", "invalidated"],
    dataFields: [
      { key: "assumptionType", label: "Type", kind: "text" },
      { key: "source", label: "Source", kind: "text" },
      { key: "validationApproach", label: "Validation approach", kind: "textarea" },
      { key: "dueDate", label: "Due date", kind: "text" },
    ],
  },
  risk: {
    type: "risk",
    label: "Risk",
    labelPlural: "Risks",
    slug: "risks",
    module: "risks",
    icon: AlertTriangle,
    description: "Risk register entries.",
    mvp: true,
    defaultStatus: "open",
    statuses: ["open", "mitigating", "accepted", "closed"],
    dataFields: [
      { key: "riskStatement", label: "Risk statement", kind: "textarea" },
      { key: "category", label: "Category", kind: "text" },
      {
        key: "likelihood",
        label: "Likelihood (1-5)",
        kind: "enum",
        options: ["1", "2", "3", "4", "5"],
      },
      {
        key: "impact",
        label: "Impact (1-5)",
        kind: "enum",
        options: ["1", "2", "3", "4", "5"],
      },
      { key: "mitigation", label: "Mitigation", kind: "textarea" },
      { key: "contingency", label: "Contingency", kind: "textarea" },
      { key: "dueDate", label: "Due date", kind: "text" },
    ],
  },
  dependency: {
    type: "dependency",
    label: "Dependency",
    labelPlural: "Dependencies",
    slug: "dependencies",
    module: "risks",
    icon: GitBranch,
    description: "External / internal dependencies.",
    mvp: true,
    defaultStatus: "open",
    statuses: ["open", "in_progress", "resolved", "at_risk"],
    dataFields: [
      { key: "isExternal", label: "External?", kind: "enum", options: ["true", "false"] },
      { key: "requiredByDate", label: "Required by", kind: "text" },
      { key: "impactIfDelayed", label: "Impact if delayed", kind: "textarea" },
    ],
  },
  experiment: {
    type: "experiment",
    label: "Experiment",
    labelPlural: "Experiments",
    slug: "experiments",
    module: "experiments",
    icon: FlaskConical,
    description: "Validation experiments.",
    mvp: true,
    defaultStatus: "planned",
    statuses: [
      "planned",
      "running",
      "analysed",
      "validated",
      "invalidated",
      "inconclusive",
    ],
    dataFields: [
      { key: "hypothesis", label: "Hypothesis", kind: "textarea" },
      { key: "objective", label: "Objective", kind: "textarea" },
      { key: "method", label: "Method", kind: "textarea" },
      { key: "sampleOrEnv", label: "Sample / environment", kind: "text" },
      { key: "successMetrics", label: "Success metrics", kind: "list" },
      { key: "startDate", label: "Start date", kind: "text" },
      { key: "endDate", label: "End date", kind: "text" },
      { key: "resultSummary", label: "Result summary", kind: "textarea" },
      { key: "recommendation", label: "Recommendation", kind: "textarea" },
      {
        key: "template",
        label: "Template",
        kind: "enum",
        options: [
          "generic",
          "voice_quality",
          "asr_accuracy",
          "latency",
          "interruption",
          "transfer_handoff",
          "outbound_workflow",
          "memory_recall",
          "post_call_summary",
        ],
      },
      { key: "rubricQuality", label: "Rubric: quality (1-5)", kind: "text" },
      { key: "rubricReliability", label: "Rubric: reliability (1-5)", kind: "text" },
      { key: "rubricCost", label: "Rubric: cost (1-5)", kind: "text" },
      { key: "rubricSpeed", label: "Rubric: speed (1-5)", kind: "text" },
      { key: "rubricUx", label: "Rubric: UX (1-5)", kind: "text" },
      { key: "rubricRisk", label: "Rubric: risk (1-5)", kind: "text" },
    ],
  },
  researchItem: {
    type: "researchItem",
    label: "Research item",
    labelPlural: "Research items",
    slug: "research",
    module: "research",
    icon: BookOpen,
    description: "Market / competitor / customer research.",
    mvp: true,
    defaultStatus: "captured",
    statuses: ["captured", "summarised", "actioned"],
    dataFields: [
      { key: "sourceType", label: "Source type", kind: "text" },
      { key: "sourceRef", label: "Source URL / ref", kind: "text" },
      { key: "date", label: "Date", kind: "text" },
      { key: "authorOrSource", label: "Author / source", kind: "text" },
      { key: "keyFindings", label: "Key findings", kind: "list" },
    ],
  },
  meetingSummary: {
    type: "meetingSummary",
    label: "Meeting summary",
    labelPlural: "Meeting summaries",
    slug: "meetings",
    module: "research",
    icon: MessagesSquare,
    description: "Interview, call and meeting summaries.",
    mvp: true,
    defaultStatus: "captured",
    statuses: ["captured", "summarised", "actioned"],
    dataFields: [
      { key: "participants", label: "Participants", kind: "list" },
      { key: "date", label: "Date", kind: "text" },
      { key: "context", label: "Context", kind: "textarea" },
      { key: "topInsights", label: "Top insights", kind: "list" },
      { key: "objections", label: "Objections", kind: "list" },
      { key: "opportunities", label: "Opportunities", kind: "list" },
      { key: "followups", label: "Follow-up actions", kind: "list" },
    ],
  },
  architectureComponent: {
    type: "architectureComponent",
    label: "Architecture component",
    labelPlural: "Architecture components",
    slug: "components",
    module: "architecture",
    icon: Boxes,
    description: "Component catalogue entry.",
    mvp: true,
    defaultStatus: "proposed",
    statuses: ["proposed", "in_use", "deprecated", "rejected"],
    dataFields: [
      { key: "function", label: "Function", kind: "textarea" },
      {
        key: "vendorOrInternal",
        label: "Vendor / internal",
        kind: "enum",
        options: ["vendor", "internal"],
      },
      { key: "maturity", label: "Maturity", kind: "text" },
      { key: "criticality", label: "Criticality", kind: "text" },
    ],
  },
  architectureOption: {
    type: "architectureOption",
    label: "Architecture option",
    labelPlural: "Architecture options",
    slug: "arch-options",
    module: "architecture",
    icon: Cpu,
    description: "Candidate architecture / provider option.",
    mvp: true,
    defaultStatus: "proposed",
    statuses: ["proposed", "in_use", "deprecated", "rejected"],
    dataFields: [
      {
        key: "domain",
        label: "Domain",
        kind: "enum",
        options: [
          "telephony",
          "orchestration",
          "memory",
          "frontend",
          "auth",
          "hosting",
          "observability",
        ],
      },
      { key: "criteriaScores", label: "Criteria scores", kind: "textarea" },
    ],
  },
  telephonyRecord: {
    type: "telephonyRecord",
    label: "Telephony record",
    labelPlural: "Telephony records",
    slug: "telephony",
    module: "architecture",
    icon: Phone,
    description: "Specialised telephony evaluation.",
    mvp: true,
    defaultStatus: "proposed",
    statuses: ["proposed", "in_use", "deprecated", "rejected"],
    dataFields: [
      { key: "provider", label: "Provider", kind: "text" },
      { key: "callPath", label: "Call path", kind: "textarea" },
      { key: "inboundHandling", label: "Inbound handling", kind: "textarea" },
      { key: "outboundHandling", label: "Outbound handling", kind: "textarea" },
      { key: "numberMgmt", label: "Number management", kind: "textarea" },
      { key: "sipPstnAssumptions", label: "SIP / PSTN assumptions", kind: "textarea" },
      { key: "fallbackModel", label: "Fallback model", kind: "textarea" },
      { key: "recordingAssumptions", label: "Recording assumptions", kind: "textarea" },
      { key: "consentImplications", label: "Consent implications", kind: "textarea" },
      { key: "latencyNotes", label: "Latency notes", kind: "textarea" },
      { key: "failureModes", label: "Failure modes", kind: "textarea" },
    ],
  },
  memoryModelRecord: {
    type: "memoryModelRecord",
    label: "Memory model",
    labelPlural: "Memory model records",
    slug: "memory",
    module: "architecture",
    icon: Brain,
    description: "Memory design records.",
    mvp: true,
    defaultStatus: "proposed",
    statuses: ["proposed", "in_use", "deprecated", "rejected"],
    dataFields: [
      {
        key: "memoryType",
        label: "Memory type",
        kind: "enum",
        options: ["personal", "relationship", "policy", "preferences"],
      },
      { key: "retentionLogic", label: "Retention logic", kind: "textarea" },
      { key: "explainabilityControls", label: "Explainability controls", kind: "textarea" },
      { key: "deletionRules", label: "Deletion rules", kind: "textarea" },
    ],
  },
  environment: {
    type: "environment",
    label: "Environment",
    labelPlural: "Environments",
    slug: "environments",
    module: "architecture",
    icon: Server,
    description: "Environment tracker.",
    mvp: false,
    defaultStatus: "not_ready",
    statuses: ["not_ready", "in_progress", "ready"],
    dataFields: [
      {
        key: "name",
        label: "Name",
        kind: "enum",
        options: ["dev", "staging", "demo", "pilot", "production"],
      },
      { key: "differences", label: "Differences", kind: "textarea" },
    ],
  },
  pricingModel: {
    type: "pricingModel",
    label: "Pricing model",
    labelPlural: "Pricing models",
    slug: "pricing-models",
    module: "pricing",
    icon: DollarSign,
    description: "Pricing model records.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "current", "retired"],
    dataFields: [
      { key: "structure", label: "Structure", kind: "textarea" },
      { key: "subscriptionAssumptions", label: "Subscription assumptions", kind: "textarea" },
      { key: "includedUsage", label: "Included usage", kind: "textarea" },
      { key: "overages", label: "Overages", kind: "textarea" },
      { key: "setupFees", label: "Setup fees", kind: "text" },
      { key: "servicesRevenue", label: "Services revenue", kind: "text" },
      { key: "cogsAssumptions", label: "COGS assumptions", kind: "textarea" },
      { key: "grossMarginEstimate", label: "Gross margin estimate", kind: "text" },
      { key: "commercialRisks", label: "Commercial risks", kind: "list" },
      { key: "targetSegmentFit", label: "Target segment fit", kind: "text" },
    ],
  },
  package: {
    type: "package",
    label: "Package",
    labelPlural: "Packages",
    slug: "packages",
    module: "pricing",
    icon: PackageIcon,
    description: "Product packages.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "current", "retired"],
    dataFields: [
      { key: "targetCustomer", label: "Target customer", kind: "text" },
      { key: "usageIncluded", label: "Usage included", kind: "textarea" },
      { key: "exclusions", label: "Exclusions", kind: "list" },
      { key: "onboardingModel", label: "Onboarding model", kind: "textarea" },
      { key: "supportModel", label: "Support model", kind: "textarea" },
      { key: "commercialGuardrails", label: "Commercial guardrails", kind: "textarea" },
    ],
  },
  unitEconomicsInput: {
    type: "unitEconomicsInput",
    label: "Unit economics input",
    labelPlural: "Unit economics inputs",
    slug: "unit-economics",
    module: "pricing",
    icon: Calculator,
    description: "Named cost / revenue input lines.",
    mvp: false,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "current", "retired"],
    dataFields: [
      { key: "driver", label: "Driver", kind: "text" },
      { key: "value", label: "Value", kind: "number" },
      { key: "unit", label: "Unit", kind: "text" },
    ],
  },
  pricingScenario: {
    type: "pricingScenario",
    label: "Pricing scenario",
    labelPlural: "Pricing scenarios",
    slug: "scenarios",
    module: "pricing",
    icon: Gauge,
    description: "Compared pricing scenarios.",
    mvp: false,
    defaultStatus: "draft",
    statuses: ["draft", "under_review", "current", "retired"],
  },
  useCase: {
    type: "useCase",
    label: "Use case",
    labelPlural: "Use cases",
    slug: "use-cases",
    module: "gtm",
    icon: Briefcase,
    description: "GTM use cases.",
    mvp: true,
    defaultStatus: "draft",
    statuses: ["draft", "approved", "retired"],
    dataFields: [
      { key: "customerProblem", label: "Customer problem", kind: "textarea" },
      { key: "actor", label: "Actor", kind: "text" },
      { key: "workflowSummary", label: "Workflow summary", kind: "textarea" },
      { key: "valueProp", label: "Value proposition", kind: "textarea" },
      { key: "proofNeeded", label: "Proof needed", kind: "textarea" },
    ],
  },
  messagingFramework: {
    type: "messagingFramework",
    label: "Messaging framework",
    labelPlural: "Messaging frameworks",
    slug: "messaging",
    module: "gtm",
    icon: Megaphone,
    description: "Messaging artefacts.",
    mvp: false,
    defaultStatus: "draft",
    statuses: ["draft", "approved", "retired"],
  },
  account: {
    type: "account",
    label: "Account",
    labelPlural: "Accounts",
    slug: "accounts",
    module: "gtm",
    icon: Building,
    description: "Pilot / target accounts.",
    mvp: true,
    defaultStatus: "prospect",
    statuses: ["prospect", "engaged", "piloting", "won", "lost", "dropped"],
    dataFields: [
      { key: "sector", label: "Sector", kind: "text" },
      { key: "fitScore", label: "Fit score (1-5)", kind: "text" },
      { key: "keyContacts", label: "Key contacts", kind: "list" },
      { key: "nextStep", label: "Next step", kind: "textarea" },
      { key: "concerns", label: "Concerns", kind: "list" },
    ],
  },
  launchChecklistItem: {
    type: "launchChecklistItem",
    label: "Launch item",
    labelPlural: "Launch checklist",
    slug: "launch",
    module: "gtm",
    icon: Rocket,
    description: "Launch readiness checklist.",
    mvp: false,
    defaultStatus: "not_started",
    statuses: ["not_started", "in_progress", "ready", "blocked"],
    dataFields: [
      {
        key: "area",
        label: "Area",
        kind: "enum",
        options: [
          "sales_deck",
          "website",
          "demo",
          "references",
          "onboarding",
          "legal",
          "support",
          "pricing",
        ],
      },
      { key: "blocker", label: "Blocker", kind: "textarea" },
    ],
  },
};

export const ALL_ENTITIES: EntityMeta[] = Object.values(ENTITIES);
export const MVP_ENTITIES: EntityMeta[] = ALL_ENTITIES.filter((e) => e.mvp);

export const ENTITIES_BY_SLUG: Record<string, EntityMeta> = Object.fromEntries(
  ALL_ENTITIES.map((e) => [e.slug, e]),
);

export function entityBySlug(slug: string): EntityMeta | undefined {
  return ENTITIES_BY_SLUG[slug];
}

export function entityByType(type: RecordType): EntityMeta {
  return ENTITIES[type];
}

export const MODULES: { key: ModuleKey; label: string; entities: RecordType[] }[] = [
  {
    key: "strategy",
    label: "Strategy",
    entities: ["vision", "thesis", "problem", "icp", "differentiator"],
  },
  { key: "roadmap", label: "Roadmap", entities: ["epic", "feature", "story"] },
  { key: "decisions", label: "Decisions", entities: ["decision"] },
  {
    key: "risks",
    label: "Risks & assumptions",
    entities: ["assumption", "risk", "dependency"],
  },
  { key: "experiments", label: "Experiments", entities: ["experiment"] },
  {
    key: "research",
    label: "Research",
    entities: ["researchItem", "meetingSummary"],
  },
  {
    key: "architecture",
    label: "Architecture",
    entities: [
      "architectureComponent",
      "architectureOption",
      "telephonyRecord",
      "memoryModelRecord",
      "environment",
    ],
  },
  {
    key: "pricing",
    label: "Pricing & packaging",
    entities: ["pricingModel", "package", "unitEconomicsInput", "pricingScenario"],
  },
  {
    key: "gtm",
    label: "GTM",
    entities: ["persona", "useCase", "messagingFramework", "account", "launchChecklistItem"],
  },
  {
    key: "delivery",
    label: "Delivery",
    entities: ["idea", "task", "milestone"],
  },
];
